# Comparer les branches de detection

Ce notebook lance les memes cas de test centralises contre les branches activees : `generic`, `spacy`, `gliner`, `regex`.

Les interrupteurs de branches sont dans la premiere cellule de code.

In [ ]:
from pathlib import Path
import os
import sys
import pandas as pd

def find_project_root(start_path: Path) -> Path:
    for candidate in (start_path, *start_path.parents):
        if (candidate / "src" / "compliance_nlp").exists() and (candidate / "configs").exists():
            return candidate
    raise FileNotFoundError("Impossible de trouver la racine du projet depuis le dossier courant.")


ROOT = find_project_root(Path.cwd().resolve())

SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

ENABLE_GENERIC_BRANCH = False
ENABLE_SPACY_BRANCH = False
ENABLE_GLINER_BRANCH = True
ENABLE_REGEX_BRANCH = False

MODEL_CACHE_DIR = r"D:\Workspaces\ModelCache"
MODEL_STORE_DIR = r"D:\Workspaces\modelStore"
SPACY_MODEL = rf"{MODEL_STORE_DIR}\fr_core_news_md"
SPACY_SYNONYMS_PATH = ROOT / "configs" / "spacy_synonyms.csv"
JEUXDEMOTS_STORE_PATH = Path(MODEL_STORE_DIR) / "jeuxdemots"
GLINER_MODEL = rf"{MODEL_STORE_DIR}\gliner_multi-v2.1"
GLINER_SOURCE_MODEL = "urchade/gliner_multi-v2.1"
GLINER_THRESHOLD = 0.3
GLINER_LOCAL_FILES_ONLY = True
GLINER_LABEL_GROUPS = {
    "sante": [
        "donnee de sante",
        "maladie",
        "pathologie",
        "autisme",
        "handicap",
        "trouble du neurodeveloppement",
        "etat de sante",
        "condition medicale",
        "probleme de sante",
    ],
    "politique": [
        "ideologie politique",
        "position politique",
    ],
    "religion": ["conviction religieuse", "religion", "appartenance religieuse"],
    "syndical": ["appartenance syndicale", "engagement syndical"],
    "orientation_sexuelle": ["orientation sexuelle"],
    "origine": ["origine ethnique", "origine raciale"],
    "biometrie_genetique": ["donnee genetique", "donnee biometrique"],
    "conformite_conseil": [
        "clause beneficiaire imprecise",
        "conseil non professionnel",
        "promesse de performance",
    ],
}
GLINER_LABELS = [label for labels in GLINER_LABEL_GROUPS.values() for label in labels]

pd.set_option("display.max_colwidth", 180)

os.environ["HF_HOME"] = MODEL_CACHE_DIR
os.environ["TRANSFORMERS_CACHE"] = rf"{MODEL_CACHE_DIR}\transformers"
os.environ["HUGGINGFACE_HUB_CACHE"] = rf"{MODEL_CACHE_DIR}\hub"
os.environ["COMPLIANCE_NLP_MODEL_CACHE"] = MODEL_CACHE_DIR
os.environ["COMPLIANCE_NLP_MODEL_STORE"] = MODEL_STORE_DIR

enabled_branches = tuple(
    branch
    for branch, enabled in {
        "generic": ENABLE_GENERIC_BRANCH,
        "spacy": ENABLE_SPACY_BRANCH,
        "gliner": ENABLE_GLINER_BRANCH,
        "regex": ENABLE_REGEX_BRANCH,
    }.items()
    if enabled
)

params = {
    "enabled_branches": enabled_branches,
    "model_cache_dir": MODEL_CACHE_DIR,
    "model_store_dir": MODEL_STORE_DIR,
    "spacy_model": SPACY_MODEL,
    "spacy_synonyms_path": str(SPACY_SYNONYMS_PATH),
    "gliner_model": GLINER_MODEL,
    "gliner_threshold": GLINER_THRESHOLD,
    "gliner_local_files_only": GLINER_LOCAL_FILES_ONLY,
    "gliner_label_groups": GLINER_LABEL_GROUPS,
    "gliner_labels": GLINER_LABELS,
}
params

{'enabled_branches': ('generic', 'spacy', 'gliner', 'regex'),
 'model_cache_dir': 'D:\\Workspaces\\ModelCache',
 'model_store_dir': 'D:\\Workspaces\\modelStore',
 'spacy_model': 'D:\\Workspaces\\modelStore\\fr_core_news_md',
 'spacy_synonyms_path': 'D:\\Workspaces\\TestPresentationNLP\\configs\\spacy_synonyms.csv',
 'gliner_model': 'D:\\Workspaces\\modelStore\\gliner_multi-v2.1',
 'gliner_threshold': 0.3,
 'gliner_local_files_only': True,
 'gliner_label_groups': {'sante': ['donnee de sante',
   'maladie',
   'pathologie',
   'autisme',
   'handicap',
   'trouble du neurodeveloppement',
   'etat de sante',
   'condition medicale',
   'probleme de sante'],
  'politique': ['ideologie politique', 'position politique'],
  'religion': ['conviction religieuse', 'religion', 'appartenance religieuse'],
  'syndical': ['appartenance syndicale', 'engagement syndical'],
  'orientation_sexuelle': ['orientation sexuelle'],
  'origine': ['origine ethnique', 'origine raciale'],
  'biometrie_genetique': ['donnee genetique', 'donnee biometrique'],
  'conformite_conseil': ['clause beneficiaire imprecise',
   'conseil non professionnel',
   'promesse de performance']},
 'gliner_labels': ['donnee de sante',
  'maladie',
  'pathologie',
  'autisme',
  'handicap',
  'trouble du neurodeveloppement',
  'etat de sante',
  'condition medicale',
  'probleme de sante',
  'ideologie politique',
  'position politique',
  'conviction religieuse',
  'religion',
  'appartenance religieuse',
  'appartenance syndicale',
  'engagement syndical',
  'orientation sexuelle',
  'origine ethnique',
  'origine raciale',
  'donnee genetique',
  'donnee biometrique',
  'clause beneficiaire imprecise',
  'conseil non professionnel',
  'promesse de performance']}

In [26]:
from pathlib import Path
import os
import sys
import pandas as pd

if "find_project_root" not in globals():
    def find_project_root(start_path: Path) -> Path:
        for candidate in (start_path, *start_path.parents):
            if (candidate / "src" / "compliance_nlp").exists() and (candidate / "configs").exists():
                return candidate
        raise FileNotFoundError("Impossible de trouver la racine du projet depuis le dossier courant.")

if "ROOT" not in globals():
    ROOT = find_project_root(Path.cwd().resolve())

SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

MODEL_CACHE_DIR = globals().get("MODEL_CACHE_DIR", r"E:\Workspace\ModelCache")
MODEL_STORE_DIR = globals().get("MODEL_STORE_DIR", r"E:\Workspace\modelStore")
SPACY_MODEL = globals().get("SPACY_MODEL", rf"{MODEL_STORE_DIR}\fr_core_news_md")
SPACY_SYNONYMS_PATH = globals().get("SPACY_SYNONYMS_PATH", ROOT / "configs" / "spacy_synonyms.csv")
JEUXDEMOTS_STORE_PATH = globals().get("JEUXDEMOTS_STORE_PATH", Path(MODEL_STORE_DIR) / "jeuxdemots")
GLINER_MODEL = globals().get("GLINER_MODEL", rf"{MODEL_STORE_DIR}\gliner_multi-v2.1")
GLINER_SOURCE_MODEL = globals().get("GLINER_SOURCE_MODEL", "urchade/gliner_multi-v2.1")
GLINER_THRESHOLD = globals().get("GLINER_THRESHOLD", 0.50)
GLINER_LOCAL_FILES_ONLY = globals().get("GLINER_LOCAL_FILES_ONLY", True)
GLINER_LABEL_GROUPS = globals().get("GLINER_LABEL_GROUPS", {
    "sante": [
        "donnee de sante",
        "maladie",
        "pathologie",
        "autisme",
        "handicap",
        "trouble du neurodeveloppement",
        "etat de sante",
        "condition medicale",
        "probleme de sante",
    ],
    "politique": [
        "ideologie politique",
        "position politique",
    ],
    "religion": ["conviction religieuse", "religion", "appartenance religieuse"],
    "syndical": ["appartenance syndicale", "engagement syndical"],
    "orientation_sexuelle": ["orientation sexuelle"],
    "origine": ["origine ethnique", "origine raciale"],
    "biometrie_genetique": ["donnee genetique", "donnee biometrique"],
    "conformite_conseil": [
        "clause beneficiaire imprecise",
        "conseil non professionnel",
        "promesse de performance",
    ],
})
GLINER_LABELS = [label for labels in GLINER_LABEL_GROUPS.values() for label in labels]
enabled_branches = globals().get("enabled_branches", ("generic", "spacy", "gliner", "regex"))

os.environ["HF_HOME"] = MODEL_CACHE_DIR
os.environ["TRANSFORMERS_CACHE"] = rf"{MODEL_CACHE_DIR}\transformers"
os.environ["HUGGINGFACE_HUB_CACHE"] = rf"{MODEL_CACHE_DIR}\hub"
os.environ["COMPLIANCE_NLP_MODEL_CACHE"] = MODEL_CACHE_DIR
os.environ["COMPLIANCE_NLP_MODEL_STORE"] = MODEL_STORE_DIR

loaded_package = sys.modules.get("compliance_nlp")
if loaded_package is not None and not hasattr(loaded_package, "refresh_spacy_synonyms_from_forbidden_words"):
    for module_name in list(sys.modules):
        if module_name == "compliance_nlp" or module_name.startswith("compliance_nlp."):
            del sys.modules[module_name]

from compliance_nlp import (
    load_generic_detection_rules,
    load_whitelist_terms,
    refresh_spacy_synonyms_from_forbidden_words,
)
from compliance_nlp.pipeline import analyze_text

spacy_synonyms_count = refresh_spacy_synonyms_from_forbidden_words(
    forbidden_words_path=ROOT / "configs" / "Mots_interdits.csv",
    synonyms_path=SPACY_SYNONYMS_PATH,
    jeuxdemots_store_path=JEUXDEMOTS_STORE_PATH,
    enrich_with_jeuxdemots=True,
    allow_network=False,
    max_synonyms=5,
    min_weight=25,
)


generic_rules = load_generic_detection_rules(ROOT / "configs" / "Mots_interdits.csv")
whitelist_terms = load_whitelist_terms(ROOT / "configs" / "article9_whitelist.csv")

referentials_df = pd.DataFrame([
    {"referentiel": "generic_rules", "count": len(generic_rules)},
    {"referentiel": "whitelist_terms", "count": len(whitelist_terms)},
    {"referentiel": "spacy_synonyms", "count": spacy_synonyms_count},
    {"referentiel": "gliner_label_groups", "count": len(GLINER_LABEL_GROUPS)},
    {"referentiel": "gliner_labels", "count": len(GLINER_LABELS)},
])
referentials_df

           referentiel  count
0        generic_rules     79
1      whitelist_terms      3
2       spacy_synonyms     77
3  gliner_label_groups      8
4        gliner_labels     24

In [27]:
TEST_CASES_PATH = ROOT / "configs" / "test_cases.csv"
TEST_CASE_COLUMNS = ["case_id", "text", "control_family", "comment"]

test_cases = pd.read_csv(TEST_CASES_PATH, keep_default_na=False)
missing_columns = set(TEST_CASE_COLUMNS) - set(test_cases.columns)
if missing_columns:
    raise ValueError(f"Colonnes manquantes dans {TEST_CASES_PATH}: {sorted(missing_columns)}")

test_cases = test_cases[TEST_CASE_COLUMNS].copy()
test_cases = test_cases[["case_id", "text", "control_family", "comment"]]
test_cases

,case_id,text,control_family,comment
0,case_001,Le dossier mentionne un handicap declare par le client.,generic,Terme interdit issu de Mots_interdits: Handicap.
1,case_002,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE,generic,Terme interdit issu de Mots_interdits: cancer.

In [28]:
def finding_key(finding):
    return finding.rule_id or finding.code


def run_detector(text: str, case_id: str):
    return analyze_text(
        document_name=case_id,
        source_path="notebook",
        extracted_text=text,
        generic_rules=generic_rules,
        whitelist_terms=whitelist_terms,
        enabled_branches=enabled_branches,
        spacy_model=SPACY_MODEL,
        spacy_synonyms_path=str(SPACY_SYNONYMS_PATH),
        gliner_model=GLINER_MODEL,
        gliner_cache_dir=MODEL_CACHE_DIR,
        gliner_source_model=GLINER_SOURCE_MODEL,
        gliner_labels=GLINER_LABEL_GROUPS,
        gliner_threshold=GLINER_THRESHOLD,
        gliner_local_files_only=GLINER_LOCAL_FILES_ONLY,
    )


def empty_row(case, engine):
    return {
        "case_id": case["case_id"],
        "control_family": case["control_family"],
        "comment": case["comment"],
        "detection_status": "none",
        "decision": "aucune detection",
        "ignored_by_whitelist": False,
        "whitelist_expression": None,
        "whitelist_reason": None,
        "detection_engine": engine,
        "predicted_key": None,
        "code": None,
        "rule_id": None,
        "rule_scope": None,
        "regulatory_family": None,
        "section": None,
        "category": None,
        "matched_term": None,
        "detection_type": None,
        "score": None,
        "branch_score": None,
        "generic_score": None,
        "spacy_score": None,
        "gliner_score": None,
        "regex_score": None,
        "severity": None,
        "evidence": None,
    }


def finding_dict_to_row(case, finding, detection_status="active", whitelist_expression=None, whitelist_reason=None):
    return {
        "case_id": case["case_id"],
        "control_family": case["control_family"],
        "comment": case["comment"],
        "detection_status": detection_status,
        "decision": "detecte puis ignore par whitelist" if detection_status == "ignored_by_whitelist" else "alerte active",
        "ignored_by_whitelist": detection_status == "ignored_by_whitelist",
        "whitelist_expression": whitelist_expression,
        "whitelist_reason": whitelist_reason,
        "detection_engine": finding.get("detection_engine"),
        "predicted_key": finding.get("rule_id") or finding.get("code"),
        "code": finding.get("code"),
        "rule_id": finding.get("rule_id"),
        "rule_scope": finding.get("rule_scope"),
        "regulatory_family": finding.get("regulatory_family"),
        "section": finding.get("section"),
        "category": finding.get("category"),
        "matched_term": finding.get("matched_term"),
        "detection_type": finding.get("detection_type"),
        "score": finding.get("score"),
        "branch_score": finding.get("branch_score"),
        "generic_score": finding.get("generic_score"),
        "spacy_score": finding.get("spacy_score"),
        "gliner_score": finding.get("gliner_score"),
        "regex_score": finding.get("regex_score"),
        "severity": finding.get("severity"),
        "evidence": finding.get("evidence"),
    }


def findings_to_rows(case, analysis):
    rows = []
    for finding in analysis.findings:
        rows.append(finding_dict_to_row(case, finding.to_dict()))
    for ignored in analysis.metadata.get("whitelist_ignored_findings", []):
        rows.append(
            finding_dict_to_row(
                case,
                ignored["finding"],
                detection_status="ignored_by_whitelist",
                whitelist_expression=ignored.get("whitelist_expression"),
                whitelist_reason=ignored.get("whitelist_reason"),
            )
        )
    if not rows:
        return [empty_row(case, "none")]
    return rows

In [29]:
analyses = []
rows = []
metadata_rows = []

for _, case in test_cases.iterrows():
    analysis = run_detector(case["text"], case["case_id"])
    analyses.append(analysis)
    rows.extend(findings_to_rows(case, analysis))
    metadata_rows.append({
        "case_id": case["case_id"],
        "control_family": case["control_family"],
        "comment": case["comment"],
        "enabled_branches": " | ".join(analysis.metadata.get("enabled_branches", [])),
        "raw_finding_count": analysis.metadata.get("raw_finding_count"),
        "finding_count": analysis.metadata.get("finding_count"),
        "whitelist_ignored_count": analysis.metadata.get("whitelist_ignored_count"),
        "generic_finding_count": analysis.metadata.get("generic_finding_count"),
        "spacy_finding_count": analysis.metadata.get("spacy_finding_count"),
        "gliner_finding_count": analysis.metadata.get("gliner_finding_count"),
        "regex_finding_count": analysis.metadata.get("regex_finding_count"),
        "generic_max_score": analysis.metadata.get("generic_max_score"),
        "spacy_max_score": analysis.metadata.get("spacy_max_score"),
        "gliner_max_score": analysis.metadata.get("gliner_max_score"),
        "regex_max_score": analysis.metadata.get("regex_max_score"),
        "raw_finding_count_by_engine": analysis.metadata.get("raw_finding_count_by_engine"),
        "whitelist_ignored_count_by_engine": analysis.metadata.get("whitelist_ignored_count_by_engine"),
        "branch_errors": analysis.metadata.get("branch_errors"),
    })

results_df = pd.DataFrame(rows)
case_summary_df = pd.DataFrame(metadata_rows)
case_summary_df

,case_id,control_family,comment,enabled_branches,raw_finding_count,finding_count,whitelist_ignored_count,generic_finding_count,spacy_finding_count,gliner_finding_count,regex_finding_count,generic_max_score,spacy_max_score,gliner_max_score,regex_max_score,raw_finding_count_by_engine,whitelist_ignored_count_by_engine,branch_errors
0,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,generic | spacy | gliner | regex,3,3,0,1,1,1,0,0.90,0.90,0.66,None,"{'generic': 1, 'spacy': 1, 'gliner': 1}",{},{}
1,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,generic | spacy | gliner | regex,4,4,0,1,1,2,0,0.77,0.78,0.47,None,"{'generic': 1, 'spacy': 1, 'gliner': 2}",{},{}

In [30]:
alerts_df = results_df[results_df["predicted_key"].notna()].copy()
alerts_df.sort_values(["case_id", "detection_status", "detection_engine", "score"], ascending=[True, True, True, False])

,case_id,control_family,comment,detection_status,decision,ignored_by_whitelist,whitelist_expression,whitelist_reason,detection_engine,predicted_key,...,matched_term,detection_type,score,branch_score,generic_score,spacy_score,gliner_score,regex_score,severity,evidence
0,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,False,None,None,generic,mots_interdits_001_handicap,...,Handicap,exact,0.90,0.90,0.90,NaN,NaN,None,critical,Le dossier mentionne un handicap declare par le client.
2,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,False,None,None,gliner,gliner_handicap,...,handicap,entity,0.66,0.66,NaN,NaN,0.66,None,medium,Le dossier mentionne un handicap declare par le client.
1,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,False,None,None,spacy,mots_interdits_001_handicap,...,Handicap,exact,0.90,0.90,NaN,0.90,NaN,None,critical,Le dossier mentionne un handicap declare par le client.
3,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,False,None,None,generic,mots_interdits_060_enfants,...,enfant,root,0.77,0.77,0.77,NaN,NaN,None,high,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
6,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,False,None,None,gliner,gliner_donnee_de_sante,...,MME MADAME,entity,0.47,0.47,NaN,NaN,0.47,None,medium,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
5,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,False,None,None,gliner,gliner_donnee_de_sante,...,ENFANT,entity,0.37,0.37,NaN,NaN,0.37,None,medium,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
4,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,False,None,None,spacy,mots_interdits_060_enfants,...,enfant,lemma,0.78,0.78,NaN,0.78,NaN,None,high,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE

In [31]:
whitelist_ignored_df = alerts_df[alerts_df["ignored_by_whitelist"]].copy()
whitelist_ignored_df[[
    "case_id",
    "decision",
    "detection_engine",
    "predicted_key",
    "matched_term",
    "score",
    "whitelist_expression",
    "whitelist_reason",
    "evidence",
]].sort_values(["case_id", "detection_engine", "score"], ascending=[True, True, False])

Empty DataFrame
Columns: [case_id, decision, detection_engine, predicted_key, matched_term, score, whitelist_expression, whitelist_reason, evidence]
Index: []

In [32]:
comparison_df = (
    alerts_df.groupby(["case_id", "control_family", "comment", "detection_status", "decision", "detection_engine"], dropna=False)
    .agg(
        detection_count=("predicted_key", "size"),
        max_score=("score", "max"),
        predicted_keys=("predicted_key", lambda values: " | ".join(sorted({value for value in values if value}))),
        matched_terms=("matched_term", lambda values: " | ".join(sorted({value for value in values if value}))),
        whitelist_expressions=("whitelist_expression", lambda values: " | ".join(sorted({value for value in values if value}))),
    )
    .reset_index()
)
comparison_df

,case_id,control_family,comment,detection_status,decision,detection_engine,detection_count,max_score,predicted_keys,matched_terms,whitelist_expressions
0,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,generic,1,0.90,mots_interdits_001_handicap,Handicap,
1,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,gliner,1,0.66,gliner_handicap,handicap,
2,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,spacy,1,0.90,mots_interdits_001_handicap,Handicap,
3,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,generic,1,0.77,mots_interdits_060_enfants,enfant,
4,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,gliner,2,0.47,gliner_donnee_de_sante,ENFANT | MME MADAME,
5,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,spacy,1,0.78,mots_interdits_060_enfants,enfant,

In [33]:
count_pivot_df = comparison_df.pivot_table(
    index=["case_id", "control_family", "comment", "detection_status", "decision"],
    columns="detection_engine",
    values="detection_count",
    aggfunc="sum",
    fill_value=0,
).reset_index()
count_pivot_df

detection_engine,case_id,control_family,comment,detection_status,decision,generic,gliner,spacy
0,case_001,generic,Terme interdit issu de Mots_interdits: Handicap.,active,alerte active,1,1,1
1,case_002,generic,Terme interdit issu de Mots_interdits: cancer.,active,alerte active,1,2,1

In [34]:
score_columns = ["generic_score", "spacy_score", "gliner_score", "regex_score"]
score_view_df = alerts_df[[
    "case_id",
    "detection_status",
    "decision",
    "ignored_by_whitelist",
    "detection_engine",
    "predicted_key",
    "matched_term",
    "detection_type",
    *score_columns,
    "whitelist_expression",
    "whitelist_reason",
    "evidence",
]].sort_values(["case_id", "detection_status", "detection_engine", "predicted_key"], na_position="last")
score_view_df

,case_id,detection_status,decision,ignored_by_whitelist,detection_engine,predicted_key,matched_term,detection_type,generic_score,spacy_score,gliner_score,regex_score,whitelist_expression,whitelist_reason,evidence
0,case_001,active,alerte active,False,generic,mots_interdits_001_handicap,Handicap,exact,0.90,NaN,NaN,None,None,None,Le dossier mentionne un handicap declare par le client.
2,case_001,active,alerte active,False,gliner,gliner_handicap,handicap,entity,NaN,NaN,0.66,None,None,None,Le dossier mentionne un handicap declare par le client.
1,case_001,active,alerte active,False,spacy,mots_interdits_001_handicap,Handicap,exact,NaN,0.90,NaN,None,None,None,Le dossier mentionne un handicap declare par le client.
3,case_002,active,alerte active,False,generic,mots_interdits_060_enfants,enfant,root,0.77,NaN,NaN,None,None,None,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
5,case_002,active,alerte active,False,gliner,gliner_donnee_de_sante,ENFANT,entity,NaN,NaN,0.37,None,None,None,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
6,case_002,active,alerte active,False,gliner,gliner_donnee_de_sante,MME MADAME,entity,NaN,NaN,0.47,None,None,None,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE
4,case_002,active,alerte active,False,spacy,mots_interdits_060_enfants,enfant,lemma,NaN,0.78,NaN,None,None,None,APPELER au 06875444545 TEL MME MADAME GERE TOUT MR ET MME SOT IMPOSABLES (ENVIRON 3000/AN ) ENFANT A CHARGE

In [35]:
branch_errors_df = case_summary_df[["case_id", "branch_errors"]].copy()
branch_errors_df = branch_errors_df[branch_errors_df["branch_errors"].map(bool)]
branch_errors_df

Empty DataFrame
Columns: [case_id, branch_errors]
Index: []

## Export des resultats

Cette cellule ecrit les vues principales du notebook dans `outputs/comparaison_branches` pour permettre une reprise dans Excel ou dans le notebook d'export multi-onglets.

In [36]:
export_dir = ROOT / "outputs" / "comparaison_branches"
export_dir.mkdir(parents=True, exist_ok=True)

exports = {
    "test_cases": test_cases,
    "referentials": referentials_df,
    "case_summary": case_summary_df,
    "results_all": results_df,
    "alerts": alerts_df,
    "whitelist_ignored": whitelist_ignored_df,
    "comparison": comparison_df,
    "count_pivot": count_pivot_df,
    "score_view": score_view_df,
    "branch_errors": branch_errors_df,
}

export_paths = []
for name, dataframe in exports.items():
    path = export_dir / f"{name}.csv"
    dataframe.to_csv(path, index=False, encoding="utf-8-sig")
    export_paths.append({
        "name": name,
        "rows": len(dataframe),
        "columns": len(dataframe.columns),
        "path": str(path),
    })

export_manifest_df = pd.DataFrame(export_paths)
export_manifest_path = export_dir / "manifest.csv"
export_manifest_df.to_csv(export_manifest_path, index=False, encoding="utf-8-sig")
export_manifest_df

,name,rows,columns,path
0,test_cases,2,4,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\test_cases.csv
1,referentials,5,2,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\referentials.csv
2,case_summary,2,18,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\case_summary.csv
3,results_all,7,26,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\results_all.csv
4,alerts,7,26,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\alerts.csv
5,whitelist_ignored,0,26,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\whitelist_ignored.csv
6,comparison,6,11,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\comparison.csv
7,count_pivot,2,8,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\count_pivot.csv
8,score_view,7,15,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\score_view.csv
9,branch_errors,0,2,D:\Workspaces\TestPresentationNLP\outputs\comparaison_branches\branch_errors.csv