# Tester GLiNER sur une phrase

Ce notebook exécute uniquement la branche GLiNER sur une phrase. Il reprend le modèle, le seuil, les groupes enrichis et les distracteurs du notebook `03e_tester_comparaison_branches_V2.ipynb`.

Chaque groupe est envoyé séparément à GLiNER. Les distracteurs participent à la prédiction, puis sont exclus des alertes finales.

In [14]:
from pathlib import Path
import os
import sys
import pandas as pd


def find_project_root(start_path: Path) -> Path:
    for candidate in (start_path, *start_path.parents):
        if (candidate / "src" / "compliance_nlp").exists():
            return candidate
    raise FileNotFoundError("Impossible de trouver la racine du projet.")


ROOT = find_project_root(Path.cwd().resolve())
SRC_DIR = ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

MODEL_CACHE_DIR = r"D:\Workspaces\ModelCache"
MODEL_STORE_DIR = r"D:\Workspaces\modelStore"
GLINER_MODEL = rf"{MODEL_STORE_DIR}\gliner_multi-v2.1"
GLINER_SOURCE_MODEL = "urchade/gliner_multi-v2.1"
GLINER_THRESHOLD = 0.50
GLINER_LOCAL_FILES_ONLY = True

os.environ["HF_HOME"] = MODEL_CACHE_DIR
os.environ["TRANSFORMERS_CACHE"] = rf"{MODEL_CACHE_DIR}\transformers"
os.environ["HUGGINGFACE_HUB_CACHE"] = rf"{MODEL_CACHE_DIR}\hub"
os.environ["COMPLIANCE_NLP_MODEL_CACHE"] = MODEL_CACHE_DIR
os.environ["COMPLIANCE_NLP_MODEL_STORE"] = MODEL_STORE_DIR

pd.set_option("display.max_colwidth", 180)

In [15]:
# Paramétrage identique au notebook 03e.
GLINER_LABEL_GROUPS = {
    "sante": [
        "donnee de sante",
        "maladie",
        "pathologie",
        "autisme",
        "handicap",
        "trouble du neurodeveloppement",
        "etat de sante",
        "condition medicale",
        "probleme de sante",
    ],
    "politique": [
        "ideologie politique",
        "position politique",
    ],
    "religion": ["conviction religieuse", "religion", "appartenance religieuse"],
    "syndical": ["appartenance syndicale", "engagement syndical"],
    "orientation_sexuelle": ["orientation sexuelle"],
    "origine": ["origine ethnique", "origine raciale"],
    "biometrie_genetique": ["donnee genetique", "donnee biometrique"],
    "conformite_conseil": [
        "clause beneficiaire imprecise",
        "conseil non professionnel",
        "promesse de performance",
    ],
}

# Enrichissement identique au notebook 03e V2, sans modifier le decoupage par famille.
GLINER_LABEL_ENRICHMENTS = {
    "sante": [
        "diagnostic medical",
        "symptome medical",
        "traitement medical",
        "antecedent medical",
        "resultat d examen medical",
        "situation de handicap",
        "perte d autonomie",
    ],
    "politique": [
        "opinion politique",
        "engagement politique",
        "appartenance a un parti politique",
        "militantisme politique",
    ],
    "religion": [
        "conviction philosophique",
        "appartenance a une communaute religieuse",
        "pratique religieuse",
        "croyance religieuse",
    ],
    "syndical": [
        "adhesion a un syndicat",
        "mandat syndical",
        "activite syndicale",
        "responsabilite syndicale",
    ],
    "orientation_sexuelle": [
        "vie sexuelle",
        "preference sexuelle",
        "orientation homosexuelle",
        "orientation bisexuelle",
    ],
    "origine": [
        "appartenance ethnique",
        "groupe ethnique",
        "origine raciale declaree",
        "origine ethnique declaree",
    ],
    "biometrie_genetique": [
        "information genetique",
        "test genetique",
        "profil ADN",
        "empreinte digitale pour identification",
        "reconnaissance faciale pour identification",
        "iris pour identification",
    ],
}
for group_name, extra_labels in GLINER_LABEL_ENRICHMENTS.items():
    GLINER_LABEL_GROUPS[group_name] = list(
        dict.fromkeys([*GLINER_LABEL_GROUPS[group_name], *extra_labels])
    )

# Les distracteurs participent uniquement a la prediction de leur famille.
# Ils ne doivent jamais etre transformes en alertes.
GLINER_DISTRACTOR_GROUPS = {
    "sante": [
        "civilite",
        "nom de personne",
        "numero de telephone",
        "situation familiale",
        "personne a charge",
        "information fiscale",
        "information patrimoniale",
    ],
    "politique": [
        "direction spatiale",
        "position sur une piste",
        "orientation geographique",
        "nom de personne",
        "organisation",
        "information politique generale sans opinion personnelle",
    ],
    "religion": [
        "nom de personne",
        "sigle commercial",
        "produit financier",
        "produit de retraite",
        "organisation",
        "lieu",
        "situation familiale",
        "situation matrimoniale",
        "information fiscale",
    ],
    "syndical": [
        "nom d organisation",
        "organisation professionnelle",
        "entreprise",
        "contrat",
        "produit financier",
    ],
    "orientation_sexuelle": [
        "situation familiale",
        "situation matrimoniale",
        "conjoint ou conjointe",
        "civilite",
        "nom de personne",
    ],
    "origine": [
        "nationalite",
        "lieu de naissance",
        "adresse",
        "langue parlee",
        "nom de personne",
        "lieu geographique",
    ],
    "biometrie_genetique": [
        "photographie ordinaire",
        "signature",
        "identifiant client",
        "numero de telephone",
        "numero de contrat",
        "code administratif",
    ],
    "conformite_conseil": [
        "nom de produit",
        "marque commerciale",
        "operation financiere",
        "information patrimoniale",
    ],
}

GLINER_PREDICTION_LABEL_GROUPS = {
    group_name: list(dict.fromkeys([*sensitive_labels, *GLINER_DISTRACTOR_GROUPS.get(group_name, [])]))
    for group_name, sensitive_labels in GLINER_LABEL_GROUPS.items()
}
GLINER_DISTRACTOR_LABELS = {
    label.casefold()
    for labels in GLINER_DISTRACTOR_GROUPS.values()
    for label in labels
}

pd.DataFrame(
    [
        {
            "groupe": groupe,
            "labels_sensibles": ", ".join(labels),
            "distracteurs": ", ".join(GLINER_DISTRACTOR_GROUPS.get(groupe, [])),
            "nombre_labels_prediction": len(GLINER_PREDICTION_LABEL_GROUPS[groupe]),
        }
        for groupe, labels in GLINER_LABEL_GROUPS.items()
    ]
)

,groupe,labels
0,sante,"donnee de sante, maladie, pathologie, autisme, handicap, trouble du neurodeveloppement, etat de sante, condition medicale, probleme de sante"
1,politique,"ideologie politique, position politique"
2,religion,"conviction religieuse, religion, appartenance religieuse"
3,syndical,"appartenance syndicale, engagement syndical"
4,orientation_sexuelle,orientation sexuelle
5,origine,"origine ethnique, origine raciale"
6,biometrie_genetique,"donnee genetique, donnee biometrique"
7,conformite_conseil,"clause beneficiaire imprecise, conseil non professionnel, promesse de performance"

## Chargement du modèle

Le modèle est chargé depuis le même emplacement local que dans le notebook 03e. Sur CPU, le premier chargement peut prendre environ une minute.

In [16]:
import gliner
from compliance_nlp.gliner_detector import load_gliner_model
from compliance_nlp.text_utils import compact_text

model = load_gliner_model(
    model_name=GLINER_MODEL,
    cache_dir=MODEL_CACHE_DIR,
    source_model=GLINER_SOURCE_MODEL,
    local_files_only=GLINER_LOCAL_FILES_ONLY,
)
model.eval()

pd.Series({
    "version_gliner": getattr(gliner, "__version__", "inconnue"),
    "modele": GLINER_MODEL,
    "seuil": GLINER_THRESHOLD,
    "mode_evaluation": not model.training,
})

version_gliner                                         0.2.27
modele             D:\Workspaces\modelStore\gliner_multi-v2.1
seuil                                                     0.5
mode_evaluation                                          True
dtype: object

## Phrase à tester

Modifiez uniquement `PHRASE`. La chaîne complète est transmise à GLiNER pour chaque groupe de labels.

In [ ]:
PHRASE = """APPELER AU 06 25 99 43 09 TEL MME 
MADAME GERE TOUT 
MR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)
ENFANTS A CHARGE"""

print(repr(PHRASE))

'APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE'

In [18]:
RESULT_COLUMNS = [
    "groupe", "texte_detecte", "label", "score",
    "debut", "fin", "seuil_applique",
    "est_distracteur", "decision",
]


def tester_gliner_par_groupes(
    phrase: str,
    threshold: float,
    exclure_distracteurs: bool = True,
) -> pd.DataFrame:
    rows = []
    phrase_compacte = compact_text(phrase)
    for groupe, labels in GLINER_PREDICTION_LABEL_GROUPS.items():
        entities = model.predict_entities(
            phrase_compacte,
            list(labels),
            threshold=threshold,
        )
        for entity in entities:
            est_distracteur = entity["label"].strip().casefold() in GLINER_DISTRACTOR_LABELS
            if exclure_distracteurs and est_distracteur:
                continue
            rows.append({
                "groupe": groupe,
                "texte_detecte": entity["text"],
                "label": entity["label"],
                "score": float(entity["score"]),
                "debut": entity["start"],
                "fin": entity["end"],
                "seuil_applique": threshold,
                "est_distracteur": est_distracteur,
                "decision": "ignore distracteur" if est_distracteur else "alerte candidate",
            })
    return pd.DataFrame(rows, columns=RESULT_COLUMNS)

## Résultats retenus avec le seuil de production

Cette cellule reproduit le comportement du notebook 03e V2 : seuil de production appliqué et distracteurs exclus. Une table vide signifie qu'aucune alerte GLiNER sensible n'est retenue.

In [19]:
resultats_retenus = tester_gliner_par_groupes(PHRASE, GLINER_THRESHOLD)
resultats_retenus.sort_values("score", ascending=False, ignore_index=True)

,groupe,texte_detecte,label,score,debut,fin,seuil_applique
0,sante,MME MADAME,donnee de sante,0.723534,30,40,0.5
1,religion,MARIES IMPOSABLES,appartenance religieuse,0.508642,67,84,0.5

## Diagnostic des scores bruts

Le seuil `0.0` permet d'observer tous les rapprochements du modèle, y compris les distracteurs. Les colonnes `est_distracteur` et `decision` expliquent leur exclusion.

In [20]:
resultats_bruts = tester_gliner_par_groupes(
    PHRASE,
    threshold=0.0,
    exclure_distracteurs=False,
)
resultats_bruts.sort_values("score", ascending=False, ignore_index=True)

,groupe,texte_detecte,label,score,debut,fin,seuil_applique
0,sante,MME MADAME,donnee de sante,0.723534,30,40,0.0
1,religion,MARIES IMPOSABLES,appartenance religieuse,0.508642,67,84,0.0
2,sante,MR ET MME,donnee de sante,0.431941,52,61,0.0
3,syndical,MARIES IMPOSABLES,appartenance syndicale,0.294794,67,84,0.0
4,religion,ENFANTS A CHARGE,appartenance religieuse,0.198234,105,121,0.0
...,...,...,...,...,...,...,...
108,origine,A,origine raciale,0.000018,113,114,0.0
109,origine,(,origine raciale,0.000009,85,86,0.0
110,biometrie_genetique,A,donnee genetique,0.000007,113,114,0.0
111,biometrie_genetique,),donnee genetique,0.000005,103,104,0.0
112,biometrie_genetique,(,donnee genetique,0.000001,85,86,0.0

## Analyse complète de la phrase

GLiNER analyse la phrase compactée avec chaque groupe. Une alerte de production doit dépasser le seuil et ne pas porter un label distracteur.

In [21]:
analyse_complete = resultats_bruts.copy()
analyse_complete.insert(0, "phrase_analysee", PHRASE)

analyse_complete["alerte_au_seuil_production"] = (
    (analyse_complete["score"] >= GLINER_THRESHOLD)
    & (~analyse_complete["est_distracteur"])
)
analyse_complete.sort_values("score", ascending=False, ignore_index=True)

,phrase_analysee,groupe,texte_detecte,label,score,debut,fin,seuil_applique,alerte_au_seuil_production
0,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,sante,MME MADAME,donnee de sante,0.723534,30,40,0.0,True
1,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,religion,MARIES IMPOSABLES,appartenance religieuse,0.508642,67,84,0.0,True
2,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,sante,MR ET MME,donnee de sante,0.431941,52,61,0.0,False
3,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,syndical,MARIES IMPOSABLES,appartenance syndicale,0.294794,67,84,0.0,False
4,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,religion,ENFANTS A CHARGE,appartenance religieuse,0.198234,105,121,0.0,False
...,...,...,...,...,...,...,...,...,...
108,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,origine,A,origine raciale,0.000018,113,114,0.0,False
109,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,origine,(,origine raciale,0.000009,85,86,0.0,False
110,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,biometrie_genetique,A,donnee genetique,0.000007,113,114,0.0,False
111,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,biometrie_genetique,),donnee genetique,0.000005,103,104,0.0,False
112,APPELER AU 06 25 99 43 09 TEL MME MADAME GERE TOUT \nMR ET MME SONT MARIES IMPOSABLES (ENVIRON 3000 / AN)\nENFANTS A CHARGE,biometrie_genetique,(,donnee genetique,0.000001,85,86,0.0,False